# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdfs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.File', verbose_name='ファイル'),
        ),
    ]
