# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170106_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='class_name',
            field=models.CharField(default='未選択', max_length=255, verbose_name='授業名'),
        ),
        migrations.AddField(
            model_name='file',
            name='subject',
            field=models.CharField(choices=[('基礎科目', (('vinyl', 'Vinyl'), ('cd', 'CD'), ('EN', '英語'), ('DE', 'ドイツ語'), ('FR', 'フランス語'), ('ZH', '中国語'), ('ES', 'スペイン語'), ('JH', '情報'), ('SU', '身体運動・健康科学実習'), ('SK', '社会科学'), ('ZB', '人文科学'), ('HH', '方法基礎'), ('KZ', '基礎実験'), ('MK', '数理科学'), ('BK', '物質科学'), ('BI', '生命科学'))), ('総合科目A', (('SH', '科学史'), ('HB', '表象文化論'))), ('総合科目B', (('JL', '日本語上級'),))], default='未選択', max_length=3, verbose_name='科目名'),
        ),
        migrations.AddField(
            model_name='file',
            name='teacher',
            field=models.CharField(default='未選択', max_length=255, verbose_name='担当教員名'),
        ),
    ]
